workflows:
  ios-workflow:
    name: Build & Publish iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios-secret
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.brandon.fitnessapp

    scripts:
      - name: Flutter pub get
        script: flutter pub get
        
      - name: Apply provisioning profiles
        script: xcode-project use-profiles
        
      - name: Precache Flutter iOS artifacts
        script: |
          cd ios
          flutter precache --ios
          pod install 

      - name: Build IPA
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:    $APP_STORE_CONNECT_API_KEY_BASE64
        key_id:     $APP_STORE_CONNECT_KEY_ID
        issuer_id:  $APP_STORE_CONNECT_ISSUER_ID

        submit_to_testflight: true

      
