workflows:
  ios-workflow:
    name: Build for iOS
    environment:
      flutter: stable
    scripts:
      - name: Precache iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
