workflows:
  ios-workflow:
    name: Build & Publish iOS
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      # Tu grupo con secretos (API Key TestFlight, etc.)
      groups:
        - ios-secret

      # Firma automática usando los archivos que subiste en Code Signing → iOS signing
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.AppGisela

    scripts:
      - name: Precache Flutter iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
          cd ..

      - name: Apply provisioning profiles
        script: |
          cd ios
          # Aplica solo al proyecto Runner, no al de Pods:
          xcode-project use-profiles --project Runner.xcodeproj
          cd ..

      - name: Build IPA
        script: |
          # Este comando genera el .ipa ya firmado
          flutter build ipa 
            --export-options-plist=ios/ExportOptions.plist 
            --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:    $APP_STORE_CONNECT_API_KEY_BASE64
        key_id:     $APP_STORE_CONNECT_KEY_ID
        issuer_id:  $APP_STORE_CONNECT_ISSUER_ID
