workflows:
  ios-workflow:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios-secret
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.AppGisela

    scripts:
      - name: Clean previous builds
        script: flutter clean
        
      - name: Precache Flutter iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
            cd ios
            rm -rf Pods Podfile.lock
            pod install --verbose
            cd ..

      - name: Setup code signing on Xcode project
        script: xcode-project use-profiles

      - name: Build iOS
        script: flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      app_store_connect:
        api_key:    $APP_STORE_CONNECT_API_KEY_BASE64
        key_id:     $APP_STORE_CONNECT_KEY_ID
        issuer_id:  $APP_STORE_CONNECT_ISSUER_ID
