workflows:
  ios-workflow:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Precache iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      app_store_connect:
        ipa_path: build/ios/iphoneos/Runner.ipa   # <-- IPA generado
        api_key: $APP_STORE_CONNECT_API_KEY       # <-- Tu .p8 en base64
        api_key_id: $APP_STORE_CONNECT_KEY_ID     # <-- Key identifier (p.ej. "THHTNRG4UV")
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID   # <-- Issuer ID
        notify_testers: true
        testflight_preview: true
        release_notes: |
          • Se corrigieron bugs menores  
          • Mejoras de rendimiento  
