workflows:
  ios-workflow:
    name: Build for iOS
    max_build_duration: 60
    environment:
      flutter: stable
    triggers:
      - events: [push, pull_request]
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release 

    artifacts:
      - build/ios/iphoneos/*.ipa

    cache:
      - cache-flutter: true
      # - cache-pod: true    # ← comenta o elimina esta línea para forzar instalación limpia de pods
