workflows:
  ios-workflow:
    name: Build for iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa

    cache:
      cache_paths:
        # Cache sólo Dart/Flutter y Gradle, NO CocoaPods
        - ~/.pub-cache
        - ~/.gradle/caches
