workflows:
  ios-workflow:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      groups:
        - ios-secret

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.AppGisela

    scripts:
      - name: Clean
        script: flutter clean

      - name: Precache Flutter iOS
        script: flutter precache --ios

      - name: Flutter pub get
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
          cd ..

      - name: Apply provisioning profiles
        script: |
          cd ios
          xcode-project use-profiles --workspace Runner.xcworkspace
          cd ..

      - name: Build unsigned Xcode project
        script: |
          cd ios
          flutter build ios --release --no-codesign
          cd ..

      - name: Archive with xcodebuild
        script: |
          cd ios
          xcodebuild archive 
            -workspace Runner.xcworkspace 
            -scheme Runner 
            -configuration Release 
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive 
            DEVELOPMENT_TEAM=2AAUNCPR94 
            CODE_SIGN_STYLE=Manual 
            PROVISIONING_PROFILE_SPECIFIER="AppStore_Profile_ComExampleAppGisela"
          cd ..

      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive 
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive 
            -exportOptionsPlist ExportOptions.plist 
            -exportPath $CM_BUILD_DIR/build/ios/ipa
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:    $APP_STORE_CONNECT_API_KEY_BASE64
        key_id:     $APP_STORE_CONNECT_KEY_ID
        issuer_id:  $APP_STORE_CONNECT_ISSUER_ID
