workflows:
  ios-workflow:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Precache iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      app_store_connect:
        ipa_path: build/ios/iphoneos/Runner.ipa
        api_key_id: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxpGNRv5y/ycevAQyCFJkzfZSKtKprivKD6Yve2HhCnugCgYIKoZIzj0DAQehRANCAARTrvGRsSOxehxNY+F8gBbNBhEF6fFcmhjtKcRdAbguvxM10yBBQa0SnOpyVDlhNcykx3Z8mjvMI6k9EgeyUG4i
        issuer_id: 1f303ca7-90dc-4286-979c-3c38368b8065
        key_id: THHTNRG4UV
        notify_testers: true
        testflight_preview: true
        release_notes: |
          • Se corrigieron bugs menores  
          • Mejoras de rendimiento  
