workflows:
  ios-workflow:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      # Importa tu grupo de variables aquí:
      groups:
        - ios-secret

    scripts:
      - name: Precache iOS artifacts
        script: flutter precache --ios

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS
        script: flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY_BASE64       # proviene de ios-secrets
        api_key_id: $APP_STORE_CONNECT_KEY_ID      # idem
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID    # idem
        notify_testers: true
        testflight_preview: true
