platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_application_path
  File.dirname(File.realpath(__FILE__))
end

require File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end
